---

- name: Install aptitude
  ansible.builtin.yum:
    name: aptitude
    state: latest
    update_cache: true

- name: Install required system packages
  ansible.builtin.yum:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  rpm_key:
    key: https://download.docker.com/linux/{{ default_container_image }}/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.docker.com/linux/{{ default_container_image }}
    gpgcheck: no
    state: present

- name: Update apt and install docker-ce
  ansible.builtin.yum:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Pull default Docker image
  community.docker.docker_image:
    name: "{{ default_container_image }}"
    source: pull

- name: Create default containers
  community.docker.docker_container:
    name: "{{ default_container_name }}{{ item }}"
    image: "{{ default_container_image }}"
    command: "{{ default_container_command }}"
    state: present
  with_sequence: count={{ container_count }}